name: Pylint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python dependencties
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          git branch -a
      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py') --exit-zero
